apiVersion: extensions/v1beta1
kind: Ingress
metadata:  
  name: nginx-test
spec:  
  rules:    
    - host: www.testkube.com      
      http:        
        paths:        
        - path: /          
          backend:            
            serviceName: nginx-svc            
            servicePort: 80
