apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: myapp
        image: nginx:latest
        env:
        - name: GET-HOSTS-FROM
          value: dns
        ports:
        - containerPort: 80
