alertmanagerFiles:
  alertmanager.yml:
    global:
      smtp_smarthost: 'smtp.163.com:25'
      smtp_from: 'xxxx@163.com'
      smtp_auth_username: 'xxxx@163.com'
      smtp_auth_password: '*********'
      smtp_require_tls: false

    templates:
      - '/etc/config/*.tmpl'

    route:
      group_by: ['alertname', 'pod_name']
      group_wait: 10s
      group_interval: 5m
      #receiver: AlertMail
      receiver: dingtalk
      repeat_interval: 1h

    receivers:
    - name: 'AlertMail'
      email_configs:
      - send_resolved: true
        to: 'xxxx@163.com'

    - name: 'wechat'
      wechat_configs:
      - send_resolved: true
        api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
        api_secret: 'xxxxx'
        corp_id: 'xxxxx'
        agent_id: 'xxx'
        to_user: '@all'
        message: '{{ template "wechat.default.message" . }}'     

    - name: dingtalk
      webhook_configs:
      - send_resolved: false
        # 需要运行插件 dingtalk-webhook.yaml，详情阅读 docs/guide/prometheus.md
        url: http://webhook-dingtalk.monitoring.svc.cluster.local:8060/dingtalk/webhook1/send

