{
 "title": "aps_monitor_tenant_resource",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" },
   { "name": "tenantId", "query": "label_values(label_tenantId)" },
   { "name": "projectId" },
   { "name": "apsInstance" }
  ]
 },
 "panels": [
  { "title": "工作负载", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(label_tenantId,namespace) (\r\n\t(sum by(pod_name,namespace)(rate(container_cpu_usage_seconds_total{namespace=~\"^$namespace\",container_name=\"\"}[1m]))) * on(pod_name) \r\n\tgroup_left(label_tenantId) (label_join(kube_pod_labels{namespace=~\"^$namespace\",label_tenantId=~\"^$tenantId\",label_tenantId!=\"\",label_apsInstance=~\"$apsInstance\"}\r\n,\"pod_name\",\",\",\"pod\")))\r\n/\r\n\r\nsum by(label_tenantId,namespace)(\r\n  (sum by(pod,namespace)(kube_pod_container_resource_limits{namespace=~\"^$namespace\",resource=\"cpu\",pod=~\"^.*\"}))\r\n  *on(pod)group_left(label_tenantId)\r\n  (\r\n    (kube_pod_labels{namespace=~\"^$namespace\",label_tenantId=~\"^$tenantId\",label_apsInstance=~\"$apsInstance\",label_projectId=~\"^$projectId\"})*on(pod)group_left()\r\n    (kube_pod_status_phase{phase=\"Running\"})\r\n  )\r\n) *100\r\n",
     "legendFormat": "value"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by(label_tenantId,namespace)(\n  (sum by(pod_name,namespace)(container_accelerator_duty_cycle{namespace =~\"^$namespace\"})) * on(pod_name) \n  group_left(label_tenantId) (label_join(kube_pod_labels{namespace=~\"^$namespace\",label_tenantId=~\"^$tenantId\",label_tenantId!=\"\",label_apsInstance=~\"$apsInstance\"},\"pod_name\",\",\",\"pod\"))\n)",
     "legendFormat": "value"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by(label_tenantId,namespace)(sum by(pod_name,namespace)(container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name=~\".*\"}) \n*on(pod_name)group_left(label_tenantId)\n(label_join(kube_pod_labels{namespace=~\"^$namespace\",label_tenantId=~\"^$tenantId\",label_tenantId!=\"\",label_apsInstance=~\"^$apsInstance\"},\"pod_name\",\",\",\"pod\")))",
     "legendFormat": "value"
    }
   ]
  },
  { "title": "存储空间", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum(aps_tenant_filestore_usage{tenant_id=~\"^$tenantId\",apsInstance=\"$apsInstance\",project_id=\"all\"})",
     "legendFormat": "value"
    }
   ]
  },
  {
   "title": "资源总览",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU资源总览",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum by(label_tenantId,namespace)(\n  (sum by(pod_name,namespace)(rate(container_cpu_usage_seconds_total{namespace=~\"^$namespace\",container_name=\"\"}[1m])))\n  * on(pod_name)group_left(label_tenantId)(label_join(kube_pod_labels{namespace=~\"^$namespace\",label_tenantId=~\"^$tenantId\",label_tenantId!=\"\",label_apsInstance=~\"^$apsInstance\"},\"pod_name\",\",\",\"pod\"))\n)"
      },
      {
       "expr": "sum by(label_tenantId,namespace)( \n  (sum by(pod,namespace)(kube_pod_container_resource_requests{namespace=~\"^$namespace\",resource=\"cpu\",pod=~\".*\"}))\n  * on(pod) group_left(label_tenantId)\n   (\n    (kube_pod_labels{namespace=~\"^$namespace\",label_tenantId=~\"^$tenantId\",label_tenantId!=\"\",label_apsInstance=~\"^$apsInstance\"})*on(pod)group_left()\n      (kube_pod_status_phase{phase=\"Running\"})\n  )\n)"
      },
      {
       "expr": "sum by(label_tenantId,namespace)(\n  (sum by(pod,namespace)(kube_pod_container_resource_limits{namespace=~\"^$namespace\",resource=\"cpu\",pod=~\".*\"}))\n  * on(pod) group_left(label_tenantId)\n  (\n    (kube_pod_labels{namespace=~\"^$namespace\",label_tenantId=~\"^$tenantId\",label_tenantId!=\"\",label_apsInstance=~\"^$apsInstance\"})*on(pod)group_left()\n    (kube_pod_status_phase{phase=\"Running\"})\n\t)\n)"
      }
     ]
    },
    {
     "title": "MEM资源总览",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum by(label_tenantId,namespace)(\n  (sum by(pod_name,namespace)(container_memory_working_set_bytes{namespace=~\"^$namespace\",container_name=~\".*\",image!=\"\",name=~\"^k8s_.*\"}))\n  * on(pod_name) group_left(label_tenantId)\n  (label_join(kube_pod_labels{namespace=~\"^$namespace\",label_tenantId=~\"^$tenantId\",label_tenantId!=\"\",label_apsInstance=~\"^$apsInstance\"},\"pod_name\",\",\",\"pod\"))\n)"
      },
      {
       "expr": "sum by(label_tenantId,namespace)(\n  (sum by(pod,namespace)(kube_pod_container_resource_requests{namespace=~\"^$namespace\",resource=\"memory\",pod=~\".*\"}))\n  * on(pod)group_left(label_tenantId)\n  (\n    (kube_pod_labels{namespace=~\"^$namespace\",label_tenantId=~\"^$tenantId\",label_tenantId!=\"\",label_apsInstance=~\"^$apsInstance\"})*on(pod)group_left()\n      (kube_pod_status_phase{phase=\"Running\"})\n  )\n)"
      },
      {
       "expr": "sum by(label_tenantId,namespace)(\n  (sum by(pod,namespace)(kube_pod_container_resource_limits{namespace=~\"^$namespace\",resource=\"memory\",pod=~\".*\"}))\n  * on(pod)group_left(label_tenantId)\n  (\n    (kube_pod_labels{namespace=~\"^$namespace\",label_tenantId=~\"^$tenantId\",label_tenantId!=\"\",label_apsInstance=~\"^$apsInstance\"})*on(pod)group_left()\n    (kube_pod_status_phase{phase=\"Running\"})\n\t)\n)"
      }
     ]
    },
    {
     "title": "GPU资源总览",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum by(label_tenantId)(\r\n\tsum by(label_tenantId,pod_mame)(\r\n\t\t(container_accelerator_duty_cycle{namespace=~\"^$namespace\"})*on(pod_name)group_left(label_tenantId)\r\n\t\t(label_join(kube_pod_labels{namespace=~\"^$namespace\",label_projectId!=\"\",label_tenantId=~\"^$tenantId\"},\"pod_name\",\",\",\"pod\"))\r\n\t)* on(pod_mame)group_left()\r\n\tlabel_join(kube_pod_container_resource_limits{namespace=~\"^$namespace\",resource=\"nvidia_com_gpu\",pod=~\".*\"},\"pod_mame\",\",\",\"pod\")\r\n)/100"
      },
      {
       "expr": "sum by(label_tenantId,namespace)(\r\n  sum by(pod)(kube_pod_container_resource_requests{namespace=~\"^$namespace\",resource=\"nvidia_com_gpu\"}) \r\n  * on(pod)group_left(label_tenantId)\r\n  (\r\n      (kube_pod_labels{namespace=~\"^$namespace\",label_tenantId=~\"^$tenantId\",label_projectId!=\"\",label_apsInstance=~\"^$apsInstance\"})*on(pod)group_left()\r\n      (kube_pod_status_phase{phase=\"Running\"})\r\n  )\r\n)"
      },
      {
       "expr": "sum by(label_tenantId,namespace)(\r\n  (sum by(pod)(kube_pod_container_resource_limits{namespace=~\"^$namespace\",resource=\"nvidia_com_gpu\"}))\r\n  *on(pod)group_left(label_tenantId)\r\n  (\r\n      (kube_pod_labels{namespace=~\"^$namespace\",label_tenantId=~\"^$tenantId\",label_projectId!=\"\",label_apsInstance=~\"^$apsInstance\"})*on(pod)group_left()\r\n      (kube_pod_status_phase{phase=\"Running\"})\r\n  )\r\n)"
      }
     ]
    }
   ]
  },
  { "title": "单机资源", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "单机资源CPU",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum by(label_tenantId,label_projectId,label_startAt,label_containerName,label_serviceId,namespace) (\r\n\t(sum by(pod_name,namespace)(rate(container_cpu_usage_seconds_total{namespace=~\"^.*\",container_name=\"\"}[1m]))) \r\n\t* on(pod_name) group_left(label_tenantId,label_containerName,label_projectId,label_startAt,label_serviceId) \r\n\t(label_join(kube_pod_labels{namespace=~\"^.*\",label_tenantId=~\"^$tenantId\",label_projectId!=\"\",label_projectId=~\"^$projectId\"},\"pod_name\",\",\",\"pod\"))\r\n)"
    },
    {
     "expr": "sum by(label_tenantId,label_projectId,label_startAt,label_containerName,label_serviceId,namespace)(\r\n  (sum(kube_pod_container_resource_requests{namespace=~\"^.*\",resource=\"cpu\",pod=~\".*\"}) by(pod,namespace))\r\n  *on(pod)group_left(label_tenantId,label_containerName,label_projectId,label_startAt,label_serviceId)\r\n  (\r\n    (kube_pod_labels{namespace=~\"^.*\",label_tenantId=~\"^$tenantId\",label_projectId!=\"\",label_tenantId!=\"\",label_projectId=~\"^$projectId\"})*on(pod)group_left()\r\n    (kube_pod_status_phase{phase=\"Running\"})\r\n  )\r\n) "
    },
    {
     "expr": "sum by(label_tenantId,label_projectId,label_startAt,label_containerName,label_serviceId,namespace)(\r\n  (sum by(pod,namespace)(kube_pod_container_resource_limits{namespace=~\"^.*\",resource=\"cpu\",pod=~\"^.*\"}))\r\n  *on(pod)group_left(label_tenantId,label_containerName,label_projectId,label_startAt,label_serviceId)\r\n  (\r\n    (kube_pod_labels{namespace=~\"^.*\",label_tenantId=~\"^$tenantId\",label_projectId!=\"\",label_tenantId!=\"\",label_projectId=~\"^$projectId\"})*on(pod)group_left()\r\n    (kube_pod_status_phase{phase=\"Running\"})\r\n  )\r\n) "
    }
   ]
  },
  {
   "title": "单机资源GPU",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "targets": [
    {
     "expr": "sum by(label_tenantId,label_projectId,label_startAt,label_containerName,label_serviceId,namespace) (\r\n\tcontainer_accelerator_duty_cycle{namespace=~\"^.*\"} \r\n\t* on(pod_name) group_left(label_tenantId,label_containerName,label_projectId,label_startAt,label_serviceId) \r\n\t(label_join(kube_pod_labels{namespace=~\"^.*\",label_tenantId=~\"^$tenantId\",label_projectId!=\"\",label_tenantId!=\"\",label_projectId=~\"^$projectId\"} ,\"pod_name\",\",\",\"pod\"))\r\n)"
    },
    {
     "expr": "sum by(label_tenantId,label_projectId,label_startAt,label_containerName,label_serviceId,namespace)(\r\n\t(sum by(pod,namespace) (kube_pod_container_resource_requests{namespace=~\"^.*\",resource=\"nvidia_com_gpu\"})) \r\n\t* on(pod) group_left(label_tenantId,label_containerName,label_projectId,label_startAt,label_serviceId) \r\n\t(\r\n\t  (kube_pod_labels{namespace=~\"^.*\",label_tenantId=~\"^$tenantId\",label_projectId!=\"\",label_tenantId!=\"\",label_projectId=~\"^$projectId\"})*on(pod)group_left()\r\n    (kube_pod_status_phase{phase=\"Running\"})\r\n  )\r\n)"
    },
    {
     "expr": "sum by(label_tenantId,label_projectId,label_startAt,label_containerName,label_serviceId,namespace)(\r\n\t(sum by(pod,namespace) (kube_pod_container_resource_limits{namespace=~\"^.*\",resource=\"nvidia_com_gpu\"})) \r\n\t* on(pod) group_left(label_tenantId,label_containerName,label_projectId,label_startAt,label_serviceId) \r\n\t(\r\n\t  (kube_pod_labels{namespace=~\"^.*\",label_tenantId=~\"^$tenantId\",label_projectId!=\"\",label_tenantId!=\"\",label_projectId=~\"^$projectId\"})*on(pod)group_left()\r\n    (kube_pod_status_phase{phase=\"Running\"})\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "单机资源MEM",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "targets": [
    {
     "expr": "sum by(label_tenantId,label_projectId,label_startAt,label_containerName,label_serviceId,namespace)(\r\n\tsum by(pod_name,namespace) (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name=~\".*\",namespace=~\"^$namespace\"})\r\n\t* on(pod_name) group_left(label_tenantId,label_containerName,label_projectId,label_startAt,label_serviceId) \r\n\t(label_join(kube_pod_labels{namespace=~\"^$namespace\",label_tenantId=~\"^$tenantId\",label_projectId!=\"\",label_tenantId!=\"\",label_projectId=~\"^$projectId\"} ,\"pod_name\",\",\",\"pod\"))\r\n)\r\n"
    },
    {
     "expr": "sum by(label_tenantId,label_projectId,label_startAt,label_containerName,label_serviceId,namespace) (\r\n\tsum by (pod,namespace)(kube_pod_container_resource_requests{namespace=~\"^$namespace\",resource=\"memory\",pod=~\".*\"})\r\n\t* on(pod) group_left(label_tenantId,label_containerName,label_projectId,label_startAt,label_serviceId) \r\n\t(\r\n\t  (kube_pod_labels{namespace=~\"^$namespace\",label_tenantId=~\"^$tenantId\",label_projectId!=\"\",label_tenantId!=\"\",label_projectId=~\"^$projectId\"})*on(pod)group_left()\r\n    (kube_pod_status_phase{phase=\"Running\"})\r\n  )\r\n)"
    },
    {
     "expr": "sum by(label_tenantId,label_projectId,label_startAt,label_containerName,label_serviceId,namespace) (\r\n\tsum by (pod,namespace)(kube_pod_container_resource_limits{namespace=~\"^$namespace\",resource=\"memory\",pod=~\".*\"})\r\n\t* on(pod) group_left(label_tenantId,label_containerName,label_projectId,label_startAt,label_serviceId) \r\n\t(\r\n  \t(kube_pod_labels{namespace=~\"^$namespace\",label_tenantId=~\"^$tenantId\",label_projectId!=\"\",label_tenantId!=\"\",label_projectId=~\"^$projectId\"})*on(pod)group_left()\r\n    (kube_pod_status_phase{phase=\"Running\"})\r\n\t)\r\n)"
    }
   ]
  },
  {
   "title": "分布式资源",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU（Driver）",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "sum by(project_id,start_at,task_type,tenant_id,task_id)(aps_tenant_spark_metric_usage{apsInstance=~\"^$apsInstance\",resource=\"cores\",role=\"driver\",tenant_id=~\"^$tenantId\",task_type!=\"DAAS\",project_id=~\"^$projectId\"})"
      },
      {
       "expr": "sum by(project_id,start_at,task_type,tenant_id,task_id)(aps_tenant_spark_metric_limits{apsInstance=~\"^$apsInstance\",resource=\"cores\",role=\"driver\",tenant_id=~\"^$tenantId\",task_type!=\"DAAS\",project_id=~\"^$projectId\"})"
      }
     ]
    },
    {
     "title": "MEM（Driver）",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
     "targets": [
      {
       "expr": "sum by(project_id,start_at,task_type,tenant_id,task_id)(aps_tenant_spark_metric_usage{apsInstance=~\"^$apsInstance\",resource=\"memory\",role=\"driver\",tenant_id=~\"^$tenantId\",task_type!=\"DAAS\",project_id=~\"^$projectId\"})"
      },
      {
       "expr": "sum by(project_id,start_at,task_type,tenant_id,task_id)(aps_tenant_spark_metric_limits{apsInstance=~\"^$apsInstance\",resource=\"memory\",role=\"driver\",tenant_id=~\"^$tenantId\",task_type!=\"DAAS\",project_id=~\"^$projectId\"})"
      }
     ]
    },
    {
     "title": "CPU（Executor）",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "sum by(project_id,start_at,task_type,tenant_id,task_id)(aps_tenant_spark_metric_usage{apsInstance=~\"^$apsInstance\",resource=\"cores\",role=\"executor\",tenant_id=~\"^$tenantId\",task_type!=\"DAAS\",project_id=~\"^$projectId\"})"
      },
      {
       "expr": "sum by(project_id,start_at,task_type,tenant_id,task_id)(aps_tenant_spark_metric_limits{apsInstance=~\"^$apsInstance\",resource=\"cores\",role=\"executor\",tenant_id=~\"^$tenantId\",task_type!=\"DAAS\",project_id=~\"^$projectId\"})"
      }
     ]
    },
    {
     "title": "MEM（Executor）",
     "type": "table",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
     "targets": [
      {
       "expr": "sum by(project_id,start_at,task_type,tenant_id,task_id)(aps_tenant_spark_metric_usage{apsInstance=~\"^$apsInstance\",resource=\"memory\",role=\"executor\",tenant_id=~\"^$tenantId\",task_type!=\"DAAS\",project_id=~\"^$projectId\"})"
      },
      {
       "expr": "sum by(project_id,start_at,task_type,tenant_id,task_id)(aps_tenant_spark_metric_limits{apsInstance=~\"^$apsInstance\",resource=\"memory\",role=\"executor\",tenant_id=~\"^$tenantId\",task_type!=\"DAAS\",project_id=~\"^$projectId\"})"
      }
     ]
    }
   ]
  },
  { "title": "存储资源", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "存储资源",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum by(project_id,dir)(aps_tenant_filestore_dir_usage{apsInstance=\"dev\",dir=~\"job|notebook|code|dataset|logs|modelrepo|image\",project_id=~\".*\"})"
    }
   ]
  },
  {
   "title": "租户项目存储资源Topk",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "expr": "topk(10000,sum by(project_id)(aps_tenant_filestore_dir_usage{apsInstance=\"dev\",dir=~\"job|notebook|code|dataset|logs|modelrepo|image\",project_id!=\"all\",tenant_id=~\"$tenantId\"}))"
    }
   ]
  }
 ]
}