{
 "title": "aps_model_runing_status",
 "description": "aps_model_runing_status",
 "tags": [ "aps" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   { "name": "namespace", "query": "label_values(namespace)" },
   { "name": "projectId" },
   { "name": "active" },
   { "name": "apsapp", "query": "label_values(apsapp)" },
   { "name": "tenantId" },
   { "name": "KIND" },
   { "name": "modelIds" }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\r\n    (sum by(pod_name) ((sum by(pod_name)(rate(container_cpu_usage_seconds_total{namespace=~\"^$namespace\",container_name=\"\"}[1m]))))\r\n    * on(pod_name)\r\n    (label_join(kube_pod_labels{namespace=~\"^$namespace\",label_apsapp=~\".+\",label_active=~\"^$active\",label_tenantId=~\"^$tenantId\"}, \"pod_name\", \",\", \"pod\")))\r\n)\r\n/ \r\nsum((sum(kube_pod_container_resource_limits{namespace=~\"^$namespace\",resource=\"cpu\",pod=~\".*\"}) by (pod)) * on(pod) group_left(label_modelId) (kube_pod_labels{namespace=~\"^$namespace\",label_apsapp=~\".+\",label_active=~\"^.*\",label_tenantId=~\"^$tenantId\"}))\r\n*100"
    }
   ]
  },
  {
   "title": "MEM",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\r\n(sum by(pod_name) (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$namespace\",container_name=~\".*\"})\r\n* on(pod_name)\r\n(label_join(kube_pod_labels{namespace=~\"^$namespace\",label_apsapp=~\".+\",label_active=~\"^$active\",label_tenantId=~\"^$tenantId\"}, \"pod_name\", \",\", \"pod\")))\r\n)\r\n/ \r\nsum(sum by (pod)(kube_pod_container_resource_limits{namespace=~\"^$namespace\",resource=\"memory\",pod=~\".*\"}) \r\n* on(pod)\r\n(kube_pod_labels{namespace=~\"^$namespace\",label_apsapp=~\".+\",label_active=~\"^.*\",label_tenantId=~\"^$tenantId\"})\r\n)\r\n*100"
    }
   ]
  },
  {
   "title": "GPU",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\r\ncontainer_accelerator_duty_cycle{namespace=~\"^$namespace\"} * on(pod_name)\r\n(label_join(kube_pod_labels{namespace=~\"^$namespace\",label_apsapp=~\".+\",label_active=~\"^$active\",label_tenantId=~\"^$tenantId\"} ,\"pod_name\",\",\",\"pod\"))\r\n)\r\n/\r\nsum((sum(kube_pod_container_resource_limits{namespace=~\"^$namespace\",resource=\"nvidia_com_gpu\",pod=~\".*\"}) by (pod)) * on(pod) group_left(label_modelId) (kube_pod_labels{namespace=~\"^$namespace\",label_apsapp=~\".+\",label_active=~\"^.*\",label_tenantId=~\"^$tenantId\"}))\r\n*100"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count (sum by(label_seldon_deployment_id) (kube_pod_labels{namespace=~\"^$namespace\",label_apsapp=~\".+\",label_active=~\"^$active\",label_tenantId=~\"^$tenantId\"}))",
     "legendFormat": "模型数量"
    }
   ]
  },
  {
   "title": "模型数量",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(sum by (label_seldon_deployment_id) (kube_pod_labels{namespace=~\"^$namespace\",label_apsapp=~\".+\",label_active=~\"^$active\",label_tenantId=~\"^$tenantId\"}))"
    }
   ]
  },
  {
   "title": "总访问次数",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(max by(modelId,KIND,instance,status)(max_over_time(datacanvas_server_request_total{method=\"PREDICTIONS\",active=~\"^$active\",kubernetes_namespace=~\"^$namespace\",serviceId!=\"\",modelId=~\"^$modelIds\",tenantId=~\"^$tenantId\",shadow=\"false\",KIND=~\"^$KIND\",KIND!=\"\"}[180d])))"
    }
   ]
  },
  {
   "title": "总成功率",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(max by(modelId,KIND,instance,status)(max_over_time(datacanvas_server_request_total{method=\"PREDICTIONS\",apsapp=\"model\",active=~\"^$active\",status=\"ok\",serviceId!=\"\",modelId=~\"^$modelIds\",tenantId=~\"^$tenantId\",shadow=\"false\",KIND=~\"^$KIND\"}[180d])))/\r\n(sum(max by(modelId,KIND,instance,status)(max_over_time(datacanvas_server_request_total{method=\"PREDICTIONS\",apsapp=\"model\",active=~\"^$active\",serviceId!=\"\",modelId=~\"^$modelIds\",tenantId=~\"^$tenantId\",shadow=\"false\",KIND=~\"^$KIND\"}[180d])))>0)\r\n*100"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "round(sum(increase(datacanvas_server_request_total{method=\"PREDICTIONS\",active=~\"^$active\",apsapp=\"model\",serviceId!=\"\",modelId!=\"\",tenantId=~\"^$tenantId\",shadow=\"false\",KIND=~\"^$KIND\"}[1m])))",
     "legendFormat": "请求数量"
    }
   ]
  },
  {
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(datacanvas_server_request_seconds_sum{method=\"PREDICTIONS\",active=~\"$active\",apsapp=\"model\",serviceId!=\"\",modelId!=\"\",tenantId=~\"^$tenantId\",KIND=~\"^$KIND\"}[1m]))\r\n\t/\r\n\tsum(rate(datacanvas_server_request_total{method=\"PREDICTIONS\",active=~\"$active\",apsapp=\"model\",serviceId!=\"\",modelId!=\"\",tenantId=~\"^$tenantId\",KIND=~\"^$KIND\"}[1m]))",
     "legendFormat": "平均响应时长"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(datacanvas_server_request_total{method=\"PREDICTIONS\",apsapp=\"model\",active=~\"^$active\",status=\"ok\",serviceId!=\"\",modelId!=\"\",tenantId=~\"^$tenantId\",shadow=\"false\",KIND=~\"^$KIND\"}[1h]))/\r\n(sum(rate(datacanvas_server_request_total{method=\"PREDICTIONS\",apsapp=\"model\",active=~\"^$active\",serviceId!=\"\",modelId!=\"\",tenantId=~\"^$tenantId\",shadow=\"false\",KIND=~\"^$KIND\"}[1h]))>0)*100"
    }
   ]
  }
 ]
}