{
 "title": "Main_Metrics",
 "description": "重要指标监控",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "K8S Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "ETCD Leader 状态",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "max(etcd_server_has_leader)" }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests_cpu_cores * on(pod) group_left kube_pod_status_phase{phase=\"Running\"}) / sum(kube_node_status_allocatable_cpu_cores)) * 100"
    }
   ]
  },
  {
   "title": "内存使用率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests_memory_bytes * on(pod) group_left kube_pod_status_phase{phase=\"Running\"}) / sum(kube_node_status_allocatable_memory_bytes)) * 100"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "((sum (node_filesystem_size_bytes{fstype=\"xfs\"}) - sum (node_filesystem_free_bytes{fstype=\"xfs\"})) / sum (node_filesystem_size_bytes{fstype=\"xfs\"})) * 100"
    }
   ]
  },
  {
   "title": "Pod使用率",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kube_pod_status_phase{phase=\"Running\"}) / sum(kube_node_status_allocatable_pods)) * 100"
    }
   ]
  },
  {
   "title": "APIServer请求错误率(5M)",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_count{code=~\"5..\"}[5m])) / sum(rate(apiserver_request_count[5m]))"
    }
   ]
  },
  {
   "title": "Pod状态",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (kube_pod_status_phase{phase=\"Running\"}) by(phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "sum (kube_pod_status_phase{phase=\"Pending\"}) by(phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "sum (kube_pod_status_phase{phase=\"Failed\"}) by(phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "sum (kube_pod_status_phase{phase=\"Succeeded\"}) by(phase)",
     "legendFormat": "{{ phase }}"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Unknown\"}) by(phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "容器状态",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting)",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated)",
     "legendFormat": "Terminated"
    },
    {
     "expr": "sum(delta(kube_pod_container_status_restarts_total[5m]))",
     "legendFormat": "Restarts (5M)"
    }
   ]
  },
  { "title": "主机", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "主机运行状态",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\".*\", mode='system'}) by (instance)"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\".*\"}"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'.*',fstype=~\"ext4|xfs\",mountpoint=\"/\"} * 10) / 10"
    },
    {
     "expr": "time() - node_boot_time_seconds{instance=~\".*\"}"
    },
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Cached_bytes ) / node_memory_MemTotal_bytes"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\".*\"}[2m])) by (instance)"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{instance=~'.*',fstype=~\"ext4|xfs\",mountpoint=\"/\"} / node_filesystem_size_bytes{instance=~'.*',fstype=~\"ext4|xfs\",mountpoint=\"/\"})"
    },
    { "expr": "(node_load5 * 100) / 100" },
    { "expr": "(node_load15 * 100) / 100" }
   ]
  },
  {
   "title": "主机系统平均负载",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1 ", "legendFormat": "{{instance}}:1m" },
    { "expr": "node_load5", "legendFormat": "{{instance}}:5m" },
    { "expr": "node_load15", "legendFormat": "{{instance}}:15m" }
   ]
  },
  {
   "title": "网络进带宽（in）",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "Bps", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'.*',device!~\"^cali.*|^veth.*|^tunl.*|^docker.*\"}[2m])*8",
     "legendFormat": "{{device}}_进带宽(in)"
    }
   ]
  },
  {
   "title": "网络出带宽（out）",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "bps", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'.*',device!~\"^cali.*|^veth.*|^tunl.*|^docker.*\"}[2m])*8",
     "legendFormat": "{{device}}_出带宽(out)"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Ceph Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "ceph_health_status" }
   ]
  },
  {
   "title": "Ceph 可用容量",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 27 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((ceph_cluster_total_bytes - ceph_cluster_total_used_bytes) / ceph_cluster_total_bytes ) * 100"
    }
   ]
  },
  {
   "title": "Ceph容量",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "ceph_cluster_total_bytes-ceph_cluster_total_used_bytes",
     "legendFormat": "Available"
    },
    { "expr": "ceph_cluster_total_used_bytes", "legendFormat": "Used" },
    { "expr": "ceph_cluster_total_bytes", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Redis实例",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 27 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(redis_up)" }
   ]
  },
  {
   "title": "Redis Clients",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(redis_connected_clients)" }
   ]
  },
  {
   "title": "RabbitMQ实例",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 27 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum (rabbitmq_up)", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "RabbitMQ连接数",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rabbitmq_connectionsTotal{kubernetes_name=\"rabbit-rabbitmq-ha\"})"
    }
   ]
  },
  {
   "title": "RabbitMQ Queue Messages",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready{kubernetes_name=\"rabbit-rabbitmq-ha\"}) by(queue)"
    },
    {
     "expr": "sum(rabbitmq_queue_messages_unacknowledged{kubernetes_name=\"rabbit-rabbitmq-ha\"}) by(queue)"
    },
    {
     "expr": "sum(rabbitmq_queue_messages{kubernetes_name=\"rabbit-rabbitmq-ha\"}) by(queue)"
    }
   ]
  },
  {
   "title": "PG数据库连接数",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 32 },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{state=\"active\"}) by(datname)"
    },
    {
     "expr": "sum(pg_stat_activity_count{state=\"idle\"}) by(datname)"
    },
    {
     "expr": "sum(pg_stat_activity_count{state=\"disabled\"}) by(datname)"
    },
    {
     "expr": "sum(pg_stat_activity_count{state=\"idle in transaction\"}) by(datname)"
    },
    {
     "expr": "sum(pg_stat_activity_count{state=\"fastpath function call\"}) by(datname)"
    },
    {
     "expr": "sum(pg_stat_activity_count{state=\"idle in transaction (aborted)\"}) by(datname)"
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } }
 ]
}