{
 "title": "RabbitMQ_Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(rabbitmq_running, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "$instance ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rabbitmq_up{instance=~\"$instance\",kubernetes_name=\"rabbit-rabbitmq-ha\"}"
    }
   ]
  },
  {
   "title": "Node up Stats",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_running{instance=~\"$instance\",kubernetes_name=\"rabbit-rabbitmq-ha\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Exchanges",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_exchangesTotal{instance=~\"$instance\",kubernetes_name=\"rabbit-rabbitmq-ha\"}",
     "legendFormat": "{{instance}}:exchanges"
    }
   ]
  },
  {
   "title": "Channels",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_channelsTotal{instance=~\"$instance.*\",kubernetes_name=\"rabbit-rabbitmq-ha\"}",
     "legendFormat": "{{instance}}:channels"
    }
   ]
  },
  {
   "title": "Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_consumersTotal{instance=~\"$instance.*\",kubernetes_name=\"rabbit-rabbitmq-ha\"}",
     "legendFormat": "{{instance}}:consumers"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_connectionsTotal{instance=~\"$instance.*\",kubernetes_name=\"rabbit-rabbitmq-ha\"}",
     "legendFormat": "{{instance}}:connections"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queuesTotal{instance=~\"$instance.*\",kubernetes_name=\"rabbit-rabbitmq-ha\"}",
     "legendFormat": "{{instance}}:queues"
    }
   ]
  },
  {
   "title": "Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rabbitmq_queue_messages_ready_total{instance=~\"$instance.*\",kubernetes_name=\"rabbit-rabbitmq-ha\"})",
     "legendFormat": "ready"
    },
    {
     "expr": "sum(rabbitmq_queue_messages_unacknowledged_total{instance=~\"$instance.*\",kubernetes_name=\"rabbit-rabbitmq-ha\"})",
     "legendFormat": "unacknowledged"
    },
    {
     "expr": "sum(rabbitmq_queue_messages_total{instance=~\"$instance.*\",kubernetes_name=\"rabbit-rabbitmq-ha\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Free disk spec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "rabbitmq_node_disk_free", "legendFormat": "{{ node}}:free" },
    { "expr": "rabbitmq_node_disk_free_limit", "legendFormat": "{{node}}:limit" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_node_mem_used{instance=~\"$instance\"}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_node_mem_limit{instance=~\"$instance\"}",
     "legendFormat": "{{node}}:limit"
    }
   ]
  },
  {
   "title": "FIle descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_fd_used{instance=~\"$instance\"}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_fd_total{instance=~\"$instance\"}",
     "legendFormat": "{{node}}:total"
    }
   ]
  },
  {
   "title": "Sockets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_sockets_used{instance=~\"$instance\"}",
     "legendFormat": "{{node}}:used"
    },
    {
     "expr": "rabbitmq_sockets_total{instance=~\"$instance\"}",
     "legendFormat": "{{node}}:total"
    }
   ]
  }
 ]
}