apiVersion: v1
kind: Pod
metadata:  
  name: test-pd
spec:  
  containers:  
  - image: nginx:1.7.9
    name: test-container01    
    volumeMounts:    
    - mountPath: /cache      
      name: cache-volume  
  - name: test-container02 
    image: busybox:1.32.0
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh","-c","sleep 3600"]
    volumeMounts:    
    - mountPath: /test     
      name: cache-volume  
  volumes:  
  - name: cache-volume    
    emptyDir: {}

