apiVersion: v1
kind: Pod
metadata:
  labels:  
    name: seret-test  
  name: seret-test
spec:  
  volumes:  
  - name: secrets    
    secret:      
      secretName: mysecret  
  containers:  
  - image: nginx:1.7.9    
    name: db    
    volumeMounts:    
    - name: secrets      
      mountPath: "/etc/secrets"   
      readOnly: true
