apiVersion: v1
kind: Service
metadata:
  name: nginx  
  labels:    
    app: nginx
spec:
  ports:  
  - port: 80    
    name: web  
  clusterIP: None  
  selector:    
    app: nginx
---
apiVersion: apps/v1
kind: StatefulSet   # 使用 StatefulSet 必须先建立一个 无头服务
metadata:
  name: web
spec:  
  selector:
    matchLabels:      
      app: nginx  
  serviceName: "nginx" 
  replicas: 3  
  template:    
    metadata:      
      labels:        
        app: nginx    
    spec:      
      containers:      
      - name: nginx        
        image: nginx:1.7.9        
        ports:        
        - containerPort: 80          
          name: web        
        volumeMounts:        
        - name: www     # 与下面对应   
          mountPath: /usr/share/nginx/html  
  volumeClaimTemplates:  
  - metadata:    
      name: www    
    spec:
      accessModes: ["ReadWriteOnce"]      
      storageClassName: "nfs"      
      resources:        
        requests:          
          storage: 1Gi  
