apiVersion: v1
kind: Pod
metadata:
  name: test-pod03
spec:
  containers:    
  - name: test-container    
    image: nginx:1.7.9      
    command: ["/bin/sh","-c","sleep 600s"]      
    volumeMounts:      
    - name: config-volume        
      mountPath: /etc/config  
  volumes:    
  - name: config-volume      
    configMap:        
      name: special-config  
  restartPolicy: Never
