apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-monitor-dcgm-exporter
  namespace: kube-system
  labels:
    helm.sh/chart: dcgm-exporter-2.3.1
    app.kubernetes.io/name: dcgm-exporter
    app.kubernetes.io/instance: nvidia-monitor
    app.kubernetes.io/version: "2.3.1"
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/component: "dcgm-exporter"
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: dcgm-exporter
      app.kubernetes.io/instance: nvidia-monitor
      app.kubernetes.io/component: "dcgm-exporter"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dcgm-exporter
        app.kubernetes.io/instance: nvidia-monitor
        app.kubernetes.io/component: "dcgm-exporter"
    spec:
      serviceAccountName: nvidia-monitor-dcgm-exporter
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: usedGpu
                operator: Exists

      volumes:
      - name: "pod-gpu-resources"
        hostPath:
          path: "/var/lib/kubelet/pod-resources"
      containers:
      - name: exporter
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
          runAsNonRoot: false
          runAsUser: 0

        image: "registry.aps.datacanvas.com:5000/aps/service/system/nvidia-gpu-exporter:latest"
        imagePullPolicy: "Always"
        args:
        - -f
        - /etc/dcgm-exporter/dcp-metrics-included.csv
        - -c
        - "15000"
        env:
        - name: "DCGM_EXPORTER_KUBERNETES"
          value: "true"
        - name: "DCGM_EXPORTER_LISTEN"
          value: ":9400"
        ports:
        - name: "metrics"
          containerPort: 9400
        volumeMounts:
        - name: "pod-gpu-resources"
          readOnly: true
          mountPath: "/var/lib/kubelet/pod-resources"
        livenessProbe:
          httpGet:
            path: /health
            port: 9400
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 9400
          initialDelaySeconds: 5
