apiVersion: v1
kind: Pod
metadata:
  name: probe-tcp81
spec:
  containers:
  - name: nginx
    image: nginx:1.7.9 
    livenessProbe:      
      initialDelaySeconds: 5      
      timeoutSeconds: 1      
      tcpSocket:        
        port: 81
