apiVersion: v1
kind: Pod
metadata:
  name: nsenter-159 # 修改名称
  namespace: default
spec:
  hostNetwork: true
  hostPID: true
  nodeName: 172.20.1.159 # 修改节点
  containers:
  - command:
    - nsenter
    - --target
    - "1"
    - --mount
    - --uts
    - --ipc
    - --net
    - --pid
    - --
    - bash
    - -l
    image: registry.bap.datacanvas.com:55443/kube-package/busybox:latest
    imagePullPolicy: IfNotPresent
    name: nsenter
    resources:
      limits:
        cpu: 100m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 256Mi
    securityContext:
      privileged: true
    stdin: true
    stdinOnce: true
    tty: true
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists
