apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-example
  labels:
    app: nginx
    version: latest
spec:
  containers:
  - name: app
    image: nginx:latest
    ports:
    - containerPort: 80 
  - name: app-double-port
    image: nginx:latest
    ports:
    - containerPort: 80
