apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv01
spec:
  capacity:
    storage: 2Gi  
  volumeMode: Filesystem  
  accessModes:    
  - ReadWriteOnce  
  persistentVolumeReclaimPolicy: Retain  # 回收策略 
  storageClassName: nfs  # 类名称
  nfs:    
    path: /nfsdata01
    server: 192.168.43.101
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv02
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # 回收策略
  storageClassName: test  # 类名称
  nfs:
    path: /nfsdata02
    server: 192.168.43.101
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv03
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # 回收策略
  storageClassName: nfs  # 类名称
  nfs:
    path: /nfsdata03
    server: 192.168.43.101
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv04
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # 回收策略
  storageClassName: nfs  # 类名称
  nfs:
    path: /nfsdata04
    server: 192.168.43.101
